fixtures:
  symlinks:
    'grafanadash': "#{source_dir}"
  repositories:
    'graphite': 'https://github.com/echocat/puppet-graphite.git'
    'tp': 'https://github.com/example42/puppet-tp'
    'tinydata': 'https://github.com/example42/tinydata'
    'archive': 'https://github.com/voxpupuli/puppet-archive'
    'stdlib': 'https://github.com/puppetlabs/puppetlabs-stdlib'

