HOSTS:
  centos-7-x64:
    platform: el-7-x86_64
    hypervisor : docker
    image: centos:centos7
    docker_preserve_image: true
    docker_cmd: '["/usr/sbin/init"]'
    docker_image_commands:
      - 'yum -y swap -- remove fakesystemd -- install systemd systemd-libs'
      - 'yum -y install cronie initscripts which'
      - 'yum -y update; yum clean all; yum makecache'
CONFIG:
  type: foss
